apiVersion: v1
kind: Namespace
metadata:
  name: mps
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mps-test-service-account
  namespace: mps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: use-privileged-scc
subjects:
- kind: ServiceAccount
  name: mps-test-service-account
  namespace: mps
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvidia-plugin-test
  namespace: mps
  labels:
    app: nvidia-plugin-test
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nvidia-plugin-test
  template:
    metadata:
      labels:
        app: nvidia-plugin-test
    spec:
      serviceAccount: mps-test-service-account
      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
      containers:
        - name: dcgmproftester12
          image: nvcr.io/nvidia/cloud-native/dcgm:3.3.3-1-ubi9
          command: ["/bin/sh", "-c"]
          args:
            - while true; do /usr/bin/dcgmproftester12 --no-dcgm-validation -t 1004 -d 300; sleep 30; done
          resources:
            limits:
              nvidia.com/gpu: 1
      securityContext:
        seccompProfile:
          type: Unconfined
