---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mps-test-service-account
  namespace: mps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mps-test-privileged-role-binding
  namespace: mps
subjects:
- kind: ServiceAccount
  name: mps-test-service-account
  namespace: mps
roleRef:
  kind: ClusterRole
  name: system:openshift:scc:privileged
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: sharing-demo-pod
  namespace: mps
spec:
  serviceAccountName: mps-test-service-account
  restartPolicy: OnFailure
  containers:
  - name: gpu-mps-sharing-ctr
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=4226000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    securityContext:
      runAsUser: 0
      # runAsNonRoot: false
      # allowPrivilegeEscalation: true