# This config is expected to fail if a pod
# request more than one MPS shares
version: v1
sharing:
  mps:
    failRequestsGreaterThanOne: true
    resources:
    - name: nvidia.com/gpu
      replicas: 10