# This config is expected to fail as the limit is
# 48 client CUDA contexts per-device
version: v1
sharing:
  mps:
    renameByDefault: false
    resources:
    - name: nvidia.com/gpu
      replicas: 49